name = "KittyCash"
description = "Foundations for the new kitties · KittyCash"
homepage = "https://www.kittycash.com/"
min_version = "0.25.1"

[author]
  name = "KittyCash"
  homepage = "https://www.kittycash.com/"
